In [2]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc' -O Heart_disease.csv

/bin/bash: wget --no-check-certificate https://docs.google.com/uc?export=download&id=1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc -O Heart_disease.csv: No such file or directory


In [19]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc' -O Heart_disease.csv

--2021-11-19 09:12:20--  https://docs.google.com/uc?export=download&id=1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc
Resolving docs.google.com (docs.google.com)... 142.251.33.206, 2607:f8b0:4004:837::200e
Connecting to docs.google.com (docs.google.com)|142.251.33.206|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0s-ao-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qfog2gbobcgs2korlmkauv1496h1dmge/1637313075000/02301538786532280764/*/1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc?e=download [following]
--2021-11-19 09:12:21--  https://doc-0s-ao-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qfog2gbobcgs2korlmkauv1496h1dmge/1637313075000/02301538786532280764/*/1mSDFyW-UYa0WQi9_kvYBMxUeLuxb0HIc?e=download
Resolving doc-0s-ao-docs.googleusercontent.com (doc-0s-ao-docs.googleusercontent.com)... 142.250.81.193, 2607:f8b0:4004:82f::2001
Connecting to doc-0s-ao-docs.googleusercontent.com (doc-0s-ao-docs.googl

In [20]:
import pandas as pd
data=pd.read_csv('/content/Heart_disease.csv')

In [65]:
data

ID  Age  Sex     ChestPain  RestBP  ...  Oldpeak  Slope  Ca        Thal   HD
0      1   54    1    nontypical     108  ...      0.0      1   0  reversable   No
1      2   44    1    nonanginal     140  ...      0.0      1   0      normal   No
2      3   74    0    nontypical     120  ...      0.2      1   1      normal   No
3      4   67    1  asymptomatic     125  ...      0.2      2   2  reversable  Yes
4      5   50    1    nonanginal     140  ...      0.6      2   1  reversable  Yes
..   ...  ...  ...           ...     ...  ...      ...    ...  ..         ...  ...
294  295   42    1    nonanginal     130  ...      0.0      1   0      normal   No
295  296   66    0       typical     150  ...      2.6      3   0      normal   No
296  297   44    1    nontypical     130  ...      0.0      1   0      normal   No
297  298   55    0  asymptomatic     180  ...      3.4      2   0      normal  Yes
298  299   60    0    nonanginal     102  ...      0.0      1   1      normal   No

[299 rows x 15 columns]

In [92]:
X=np.array(data.drop(['HD'],axis=1))
X

array([[1, 54, 1, ..., 1, 0, 'reversable'],
       [2, 44, 1, ..., 1, 0, 'normal'],
       [3, 74, 0, ..., 1, 1, 'normal'],
       ...,
       [297, 44, 1, ..., 1, 0, 'normal'],
       [298, 55, 0, ..., 2, 0, 'normal'],
       [299, 60, 0, ..., 1, 1, 'normal']], dtype=object)

In [108]:
Y=pd.Series(np.where(data.HD.values=='Yes',1,0), data.index)
Y=np.array(Y)
Y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [16]:
seed=1073

In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=50)

In [79]:
mlp=MLPClassifier(max_iter=500, activation='relu')
mlp  

MLPClassifier(max_iter=500)

In [111]:
b=mlp.fit(X_train,Y_train)

ValueError: ignored

In [81]:
result = b.score(X_test, y_test)
print("Accuracy: %.3f%%" % (result*100.0))

NameError: ignored

In [82]:
pred=mlp.predict(X_test)
pred

ValueError: ignored

In [83]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import Normalizer
x_train=data.iloc[:,1:-1]
y_train=data.iloc[:,-1:]

In [85]:
x_test=data.iloc[:,1:]
x_test

Age  Sex     ChestPain  RestBP  Chol  ...  Oldpeak  Slope  Ca        Thal   HD
0     54    1    nontypical     108   309  ...      0.0      1   0  reversable   No
1     44    1    nonanginal     140   235  ...      0.0      1   0      normal   No
2     74    0    nontypical     120   269  ...      0.2      1   1      normal   No
3     67    1  asymptomatic     125   254  ...      0.2      2   2  reversable  Yes
4     50    1    nonanginal     140   233  ...      0.6      2   1  reversable  Yes
..   ...  ...           ...     ...   ...  ...      ...    ...  ..         ...  ...
294   42    1    nonanginal     130   180  ...      0.0      1   0      normal   No
295   66    0       typical     150   226  ...      2.6      3   0      normal   No
296   44    1    nontypical     130   219  ...      0.0      1   0      normal   No
297   55    0  asymptomatic     180   327  ...      3.4      2   0      normal  Yes
298   60    0    nonanginal     102   318  ...      0.0      1   1      normal   No

[299 rows x 14 columns]

In [87]:
y_test=data.iloc[:,1:-1]
y_test

Age  Sex     ChestPain  RestBP  ...  Oldpeak  Slope  Ca        Thal
0     54    1    nontypical     108  ...      0.0      1   0  reversable
1     44    1    nonanginal     140  ...      0.0      1   0      normal
2     74    0    nontypical     120  ...      0.2      1   1      normal
3     67    1  asymptomatic     125  ...      0.2      2   2  reversable
4     50    1    nonanginal     140  ...      0.6      2   1  reversable
..   ...  ...           ...     ...  ...      ...    ...  ..         ...
294   42    1    nonanginal     130  ...      0.0      1   0      normal
295   66    0       typical     150  ...      2.6      3   0      normal
296   44    1    nontypical     130  ...      0.0      1   0      normal
297   55    0  asymptomatic     180  ...      3.4      2   0      normal
298   60    0    nonanginal     102  ...      0.0      1   1      normal

[299 rows x 13 columns]

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=50)

In [97]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(max_iter=500, activation='relu')
mlp     

MLPClassifier(max_iter=500)

In [99]:
from keras.utils.np_utils import to_categorical
Y_train=to_categorical(y_train,num_classes=None)
Y_test=to_categorical(y_test,num_classes=None)

ValueError: ignored

In [98]:
b=mlp.fit(X_train,Y_train)
result = b.score(X_test, Y_test)
print("Accuracy: %.3f%%" % (result*100.0))

ValueError: ignored

In [91]:
pred=mlp.predict(X_test)
pred

NotFittedError: ignored

In [73]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit(X)
Y=scaler.fit(Y)

ValueError: ignored

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

In [75]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=(6,5),random_state=5,verbose=True,learning_rate_init=0.01)
clf.fit(X_train,y_train)

ValueError: ignored

In [70]:
ypred=clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred)

ValueError: ignored

In [61]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(solver='lbfgs',alpha=1e-5, hidden_layer_sizes=(15,),random_state=1)
for i in range(10):
  clf.fit(X_train,y_train)

ValueError: ignored

In [63]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X,y=make_classification(n_samples=100,random_state=1)
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y,random_state=1)
clf=MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])

array([[0.03838405, 0.96161595]])

In [77]:
import pandas
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

array = data.values
X = array[:,0:14]
Y = array[:,14]

seed = 1073

models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('MLP', MLPClassifier()))

results = []
names = []
scoring = 'accuracy'
for name, model in models:
	kfold = model_selection.KFold(n_splits=10, random_state=seed)
	cv_results = model_selection.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
	print(msg)

fig = plt.figure()
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
plt.show()

ValueError: ignored